enabled = true
name = "Neuro-sama Song Pack"
description = "Song pack for the Neuro-sama songs!\nCurrently, this only has LIFE and BOOM."
version = "0.2"
date = "12.25.2025"
author = "Kyokura"

include = ["."]
