enabled = true
name = "Neuro-sama Song Pack"
description = "Song pack for the Neuro-sama songs!\nCurrently, this only has LIFE BOOM, and NEVER."
version = "0.3"
date = "7.01.2026"
author = "Kyokura"

include = ["."]
